#!/bin/bash

# Copyright (C) 2014-2018 Jamil Said Jr
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
## This file is part of the shredzz program. This program will attempt
## to securely delete files and folders (with overwritting, so that they 
## can't be "undeleted"), using the capabilities of the program secure-delete. 
## This program uses a two pass overwrite (for speed purposes), but that can 
## be modified to as little as one pass and as many as the Gutmann's method
## recommends (way above old DoD guidelines). This program was made to appear
## as an option in the right-click menu when clicking on a file or folder.
## A GUI pop-up instructs the user about options and files/folders that can't 
## be deleted (system files), and it won't work if user doesn't have the right 
## permissions to delete the file/folder.
##
## This program was created for and tested in Linux Debian 8.

# zenity message - IMPORTANT: if change title of zenity, must update the 
# command to kill it on other script(s)
sleep 10800 | zenity --progress --no-cancel --auto-close --pulsate --width=300 --height=200 --title="Deletion Beyond Recovery Started" --text="\nDeletion\/shredding beyond recovery for the file\/folder you selected has started. \n\nPlease note that this process can take several minutes, or even a few hours if the folder to be deleted is very big. \n\nThis window will close automatically when the deletion is completed. \n\nThis deletion\/shredding started on $(date) \n"
exit 0
