#!/bin/bash

# Copyright (C) 2014-2018 Jamil Said Jr
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
## This file is part of the upshutzz program. This program will attempt
## to automatically update OS & programs (without human assist) and then 
## shutdown your computer. This program is intended to be used when user 
## will shutdown computer, as they can just select this program and leave 
## the machine unassisted while it updates and then shuts down. The update 
## version used is the gentlier 'upgrade' command (as opposed to 'dist-upgrade')
## which will only update existing packages, but will not install new (not 
## previously installed) packages (lesser chance of system failure
## after botched update). That can be changed by using 'dist-upgrade' instead.
## This program will update all programs (including third parties) that 
## have added their repository address on the OS (all Debian programs plus 
## many third party ones). The program will also check for the flash plug-in
## and update it if installed. This program saves results of the updates 
## in dated logs located at /var/log/apt/upshutzz. A GUI interface appears
## to explain options and inform the user when the program is launched. Before
## the program perform the updates, it will look for and fix possible broken
## packages or failed past installations before proceeding.
##
## This program was created for and tested in Linux Debian 8 & 9.

#declare some variables, make sure folder exists
mkdir -p /var/log/apt/upshutzz
dirstore="/var/log/apt/upshutzz/"
logdata="$(date +"%F")"
exten="-upshutzz.log"
lognome="$dirstore$logdata$exten"

#upshutzz starts here
echo "------- System Update and Shutdown Started $(date) -------" >> "$lognome"
sleep 1

#check for software package errors and fix them
DEBIAN_FRONTEND=noninteractive dpkg --force-confdef --force-confold --configure -a >> "$lognome" 2>&1
sleep 1
DEBIAN_FRONTEND=noninteractive apt-get -y -o DPkg::options::="--force-confdef" -o DPkg::options::="--force-confold" install -f >> "$lognome" 2>&1
sleep 1
DEBIAN_FRONTEND=noninteractive dpkg --force-confdef --force-confold --configure -a >> "$lognome" 2>&1
sleep 1

# update and upgrade (update software packages). This update is considered 
# "gentle", that is, it will only update existing packages, but will not 
# install new (not previously installed) packages, so if an update
# requires a new package, it won't be installed (lesser chance of system failure
# after botched update). To change that, you may use the "deep" update
# option by changing 'upgrade' to 'dist-upgrade' on the third line below
DEBIAN_FRONTEND=noninteractive apt-get -y update >> "$lognome" 2>&1
sleep 2
DEBIAN_FRONTEND=noninteractive apt-get -y -o DPkg::options::="--force-confdef" -o DPkg::options::="--force-confold" upgrade >> "$lognome" 2>&1
sleep 2

#check for flash plug in for firefox, and if installed, update it to a 
#newer version (if available). If flash is not installed do nothing.
checkflash1="$(dpkg -s flashplugin-nonfree | grep -i "not installed")"
checkflash2="$(which update-flashplugin-nonfree)"
if [[ -z "$checkflash1" ]] || [[ -n "$checkflash2" ]]; then
DEBIAN_FRONTEND=noninteractive update-flashplugin-nonfree --install --verbose >> "$lognome" 2>&1
fi
sleep 2

#check for flash plug in for chromium, and if installed, update it to a 
#ewer version (if available). If flash is not installed do nothing.
checkflash3="$(dpkg -s pepperflashplugin-nonfree | grep -i "not installed")"
checkflash4="$(which update-pepperflashplugin-nonfree)"
if [[ -z "$checkflash3" ]] || [[ -n "$checkflash4" ]]; then
DEBIAN_FRONTEND=noninteractive update-pepperflashplugin-nonfree --install --verbose >> "$lognome" 2>&1
fi
sleep 2

#end of main upshutzz work
echo "------- System Update and Shutdown Ended $(date) -------" >> "$lognome"

#kill zenity and other scripts
killall upshutzz3 >> "$lognome" 2>&1
killall zenity >> "$lognome" 2>&1
sleep 1

#exit and shutdown system 
systemctl poweroff
exit 0
