#!/bin/bash

# Copyright (C) 2014-2018 Jamil Said Jr
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
## This file is part of the upshutzz program. This program will attempt
## to automatically update OS & programs (without human assist) and then 
## shutdown your computer. This program is intended to be used when user 
## will shutdown computer, as they can just select this program and leave 
## the machine unassisted while it updates and then shuts down. The update 
## version used is the gentlier 'upgrade' command (as opposed to 'dist-upgrade')
## which will only update existing packages, but will not install new (not 
## previously installed) packages (lesser chance of system failure
## after botched update). That can be changed by using 'dist-upgrade' instead.
## This program will update all programs (including third parties) that 
## have added their repository address on the OS (all Debian programs plus 
## many third party ones). The program will also check for the flash plug-in
## and update it if installed. This program saves results of the updates 
## in dated logs located at /var/log/apt/upshutzz. A GUI interface appears
## to explain options and inform the user when the program is launched. Before
## the program perform the updates, it will look for and fix possible broken
## packages or failed past installations before proceeding.
##
## This program was created for and tested in Linux Debian 8 & 9.

zenity --question --width=300 --height=200 --title="Update and Shutdown Computer" --text="\nATTENTION: this program will update and shutdown your computer. Use it only when you are ready to shutdown. \n\nIMPORTANT: before starting, make sure that the computer has internet access and is plugged to electricity. \nAlso, please close all open programs and files before starting. \n\nUpdates generally take between 5 and 20 minutes, but in some occasions can take up to 45 minutes or more. \n\nYou can see the results of this update on the file \/var\/log\/apt\/upshutzz4.log \n\nTo CANCEL the update and shutdown, press the button \"Cancel\"\; Otherwise, press \"Update and Shutdown\" to continue. \n" --ok-label="Update and Shutdown" --cancel-label="Cancel"
rc="$?"
if [[ "$rc" -eq 1 ]] ; then
    # user clicked Cancel
    exit 0
else
    nohup /usr/local/bin/upshutzz3 &
    nohup /usr/local/bin/upshutzz4 &
    sleep 2
fi

exit 0
