#!/bin/bash

# Copyright (C) 2014-2018 Jamil Said Jr 
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
## This file is part of the hwreportzz program. This program will attempt
## to report on some of your computer's OS and hardware characteristics 
## and run some hardware tests. The report is stored in a file located at
## /var/log/zz4-hwreport.txt
##
## This program was created for and tested in Linux Debian 8.

#os and hardware report start
echo "----------OS AND HARDWARE REPORTS START HERE-----------" >> /var/log/zz4-hwreport.txt
echo >> /var/log/zz4-hwreport.txt

#wifi card report 
echo "----------WiFI Card Report----------" >> /var/log/zz4-hwreport.txt
iwconfig | grep -i IEEE >> /var/log/zz4-hwreport.txt 2>&1
iwconfig | grep -i "Bit Rate" >> /var/log/zz4-hwreport.txt 2>&1
iwconfig | grep -i "Power Management" >> /var/log/zz4-hwreport.txt 2>&1
lspci -vvnn | grep -A 9 Network | grep -i "Network controller" >> /var/log/zz4-hwreport.txt 2>&1
lspci -vvnn | grep -A 9 Network | grep -i "Kernel" >> /var/log/zz4-hwreport.txt 2>&1
lspci | grep -i 'wifi\|wlan\|wireless' >> /var/log/zz4-hwreport.txt 2>&1
echo >> /var/log/zz4-hwreport.txt
echo "-----------------------------------------------" >> /var/log/zz4-hwreport.txt
echo >> /var/log/zz4-hwreport.txt

#ethernet card report (wired internet)
echo "----------Ethernet Card Report----------" >> /var/log/zz4-hwreport.txt
lspci | grep -i ethernet >> /var/log/zz4-hwreport.txt 2>&1
echo "-----------------------------------------------" >> /var/log/zz4-hwreport.txt
echo >> /var/log/zz4-hwreport.txt

#bluetooth report
echo "----------Bluetooth Report----------" >> /var/log/zz4-hwreport.txt
hcitool dev >> /var/log/zz4-hwreport.txt 2>&1
lspci | grep -i blue >> /var/log/zz4-hwreport.txt 2>&1
lsusb | grep -i blue >> /var/log/zz4-hwreport.txt 2>&1
echo "-----------------------------------------------" >> /var/log/zz4-hwreport.txt
echo >> /var/log/zz4-hwreport.txt

#screen report
echo '----------Screen Report (Touch?)----------' >> /var/log/zz4-hwreport.txt
screenmm="$(xdpyinfo | awk '/dimensions:/ { print $4; exit }')"
screenmmt="${screenmm:1}"
screenmmt1="${screenmmt%x*}"
screenmmt2="${screenmmt#*x}"
screenmmt1s="$((screenmmt1 * screenmmt1))"
screenmmt2s="$((screenmmt2 * screenmmt2))"
screenmmt3s="$((screenmmt1s + screenmmt2s))"
screenmmt3rooted="$(echo "scale=2; sqrt ($screenmmt3s)" | bc -l)" 
screeninches="$(echo "scale=2; $screenmmt3rooted / 25.4" | bc -l)"
screenresol="$(xdpyinfo | awk '/dimensions:/ { print $2; exit }')"
echo "Screen resolution is $screenresol" >> /var/log/zz4-hwreport.txt 2>&1
#echo "Screen in inches $screeninches" >> /var/log/zz4-hwreport.txt # screen in inches not reporting correctly, thus disabled
xinput --list | grep -i touch >> /var/log/zz4-hwreport.txt 2>&1
xinput --list | grep -i tablet >> /var/log/zz4-hwreport.txt 2>&1
udevadm info --export-db | grep -i ID_INPUT_TOUCHSCREEN >> /var/log/zz4-hwreport.txt 2>&1
udevadm info --export-db | grep -i ID_INPUT_TABLET >> /var/log/zz4-hwreport.txt 2>&1
echo "-----------------------------------------------" >> /var/log/zz4-hwreport.txt
echo >> /var/log/zz4-hwreport.txt

#hard drives report
echo "----------Hard Drive Report----------" >> /var/log/zz4-hwreport.txt
smartctl -i /dev/sda | grep -i "rotation rate" >> /var/log/zz4-hwreport.txt 2>&1
smartctl --health /dev/sda | grep -svi "Copyright" >> /var/log/zz4-hwreport.txt 2>&1
freespacendas="$(df -h | grep -i "/dev/sd" | awk '{print $4}')"
echo "Free space in GB is $freespacendas" >> /var/log/zz4-hwreport.txt
parted -l | grep -i "disk /dev/" >> /var/log/zz4-hwreport.txt 2>&1
parted -l | grep -i model >> /var/log/zz4-hwreport.txt 2>&1
lshw -class disk | grep -i  description >> /var/log/zz4-hwreport.txt 2>&1
echo "-----------------------------------------------" >> /var/log/zz4-hwreport.txt
echo >> /var/log/zz4-hwreport.txt

#memory report 
echo "----------Memory Report----------" >> /var/log/zz4-hwreport.txt
memtot="$(grep -i 'MemTotal:' /proc/meminfo | awk '{print $2}')"
memtottrunc="${memtot:0:-3}"
memtester 6M 1
  codigo="$?"; if [[ "$codigo" -ne 0 ]]; then echo "WARNING - memtester found problem with memory - code ${codigo}" >> /var/log/zz4-hwreport.txt
  else echo "Memtester test OK" >> /var/log/zz4-hwreport.txt; fi
echo "Total memory is $memtottrunc MB" >> /var/log/zz4-hwreport.txt
dmidecode -t 17 | grep -i -m 4 'Size:' >> /var/log/zz4-hwreport.txt 2>&1
dmidecode -t 17 | grep -i -m 4 'Type:' >> /var/log/zz4-hwreport.txt 2>&1
dmidecode -t 17 | grep -i -m 4 'Type Detail:' >> /var/log/zz4-hwreport.txt 2>&1
dmidecode -t 17 | grep -i -m 4 'Form Factor:' >> /var/log/zz4-hwreport.txt 2>&1
dmidecode -t 17 | grep -i -m 4 'Speed:' >> /var/log/zz4-hwreport.txt 2>&1
lshw -short -C memory >> /var/log/zz4-hwreport.txt 2>&1
echo >> /var/log/zz4-hwreport.txt
echo "-----------------------------------------------" >> /var/log/zz4-hwreport.txt
echo >> /var/log/zz4-hwreport.txt

#cd/dvd report 
echo "----------CD and DVD Report----------" >> /var/log/zz4-hwreport.txt
grep -i "Can play audio" /proc/sys/dev/cdrom/info >> /var/log/zz4-hwreport.txt 2>&1
grep -i 'Can write CD-R:' /proc/sys/dev/cdrom/info >> /var/log/zz4-hwreport.txt 2>&1
grep -i "Can write CD-RW" /proc/sys/dev/cdrom/info >> /var/log/zz4-hwreport.txt 2>&1
grep -i "Can read DVD" /proc/sys/dev/cdrom/info >> /var/log/zz4-hwreport.txt 2>&1
grep -i 'Can write DVD-R:' /proc/sys/dev/cdrom/info >> /var/log/zz4-hwreport.txt 2>&1
grep -i "Can write DVD-RAM" /proc/sys/dev/cdrom/info >> /var/log/zz4-hwreport.txt 2>&1
echo "-----------------------------------------------" >> /var/log/zz4-hwreport.txt
echo >> /var/log/zz4-hwreport.txt

#battery report
echo "----------Battery Report----------" >> /var/log/zz4-hwreport.txt
upower -i "$(upower -e | grep -i 'BAT')" | grep -i 'state:\|time to full:' >> /var/log/zz4-hwreport.txt 2>&1
echo >> /var/log/zz4-hwreport.txt
acpi -i >> /var/log/zz4-hwreport.txt 2>&1
echo >> /var/log/zz4-hwreport.txt

#web cam report
echo "----------Webcam Report----------" >> /var/log/zz4-hwreport.txt
cheese1="/sys/class/video4linux"
cheese2="/dev/video0"
cheese3="/dev/video1"
cheese4="/dev/video"
cheese5="/dev/video*"
cheese6="$(ls /dev/video*)"
cheese7="$(ls /sys/class/video4linux)"
if [ -d "$cheese1" ] || [ -d "$cheese2" ] || [ -d "$cheese3" ] || [ -d "$cheese4" ] || [ -d "$cheese5" ] ; then
echo "Found webcam $cheese6" >> /var/log/zz4-hwreport.txt 
echo "Found webcam $cheese7" >> /var/log/zz4-hwreport.txt ; else
echo "No webcam found" >> /var/log/zz4-hwreport.txt ; fi
echo "-----------------------------------------------" >> /var/log/zz4-hwreport.txt
echo >> /var/log/zz4-hwreport.txt

#OS report -- reports the primary archictecture (there may be several)
echo "----------OS Report----------" >> /var/log/zz4-hwreport.txt
check3264="$(dpkg --print-architecture)"
check3264low="${check3264,,}"
i386var="i386"
amd64var="amd64"
if [[ "$check3264low" == "$i386var" ]] ; then echo "OS is 32-bit" >> /var/log/zz4-hwreport.txt ; fi
if [[ "$check3264low" == "$amd64var" ]] ; then echo "OS is 64-bit" >> /var/log/zz4-hwreport.txt ; fi
if [[ "$check3264low" != "$i386var" ]] && [[ "$check3264low" != "$amd64var" ]] ; then echo "Cannot determine OS number of bits. Returned result was $check3264low" >> /var/log/zz4-hwreport.txt; fi
lsb_release -d >> /var/log/zz4-hwreport.txt 2>&1
uname -sr >> /var/log/zz4-hwreport.txt 2>&1
echo "-----------------------------------------------" >> /var/log/zz4-hwreport.txt
echo >> /var/log/zz4-hwreport.txt

#supported power states (s1,s3,etc)
echo "----------Suported Power States----------" >> /var/log/zz4-hwreport.txt
if [[ -e /usr/local/.extra-copies/no-hibernation.txt ]]; then echo 'WARNING - hibernation not supported - instazz4 disabled hibernation and created control file: /usr/local/.extra-copies/no-hibernation.txt' >> /var/log/zz4-hwreport.txt; fi
if [[ -e /usr/local/.extra-copies/no-suspend.txt ]]; then echo 'WARNING - suspend not supported - instazz4 disabled suspend and created control file: /usr/local/.extra-copies/no-suspend.txt' >> /var/log/zz4-hwreport.txt; fi
catcheck1="$(cat /sys/power/state)"
echo "Supported power states: $catcheck1" >> /var/log/zz4-hwreport.txt
echo >> /var/log/zz4-hwreport.txt
echo 'ADORADEAL COMMENT: What some labels mean - "mem": suspend (to ram); "disk": hibernate;' >> /var/log/zz4-hwreport.txt
echo "-----------------------------------------------" >> /var/log/zz4-hwreport.txt
echo >> /var/log/zz4-hwreport.txt

#processor report
echo "----------Processor Report----------" >> /var/log/zz4-hwreport.txt
lscpu | grep -i "Model name" >> /var/log/zz4-hwreport.txt 2>&1
lscpu | grep -i 'CPU(s):' >> /var/log/zz4-hwreport.txt 2>&1
lscpu | grep -i "CPU family" >> /var/log/zz4-hwreport.txt 2>&1
lscpu | grep -i 'Model:' >> /var/log/zz4-hwreport.txt 2>&1
lscpu | grep -i "Vendor ID" >> /var/log/zz4-hwreport.txt 2>&1
echo "-----------------------------------------------" >> /var/log/zz4-hwreport.txt
echo >> /var/log/zz4-hwreport.txt

#video card report
echo "----------Video Card Report----------" >> /var/log/zz4-hwreport.txt
lspci 2>/dev/null | grep -si 'VGA compatible controller' >> /var/log/zz4-hwreport.txt 2>&1
echo "-----------------------------------------------" >> /var/log/zz4-hwreport.txt
echo >> /var/log/zz4-hwreport.txt

#audio report
echo "----------Audio Report----------" >> /var/log/zz4-hwreport.txt
cat /proc/asound/cards >> /var/log/zz4-hwreport.txt 2>&1
arecord --list-devices >> /var/log/zz4-hwreport.txt 2>&1
aplay --list-devices >> /var/log/zz4-hwreport.txt 2>&1
echo "-----------------------------------------------" >> /var/log/zz4-hwreport.txt
echo >> /var/log/zz4-hwreport.txt

echo "----------END OF OS AND HARDWARE REPORTS-----------" >> /var/log/zz4-hwreport.txt

exit 0
