#!/bin/bash

# Copyright (C) 2014-2018 Jamil Said Jr
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
## This file is part of the alsazz (Sound Trouble Shooting) program. The 
## program will attempt to unmute and set volumes on different channels 
## on your computer. This program is useful to troubleshoot/fix computers 
## with sound problems.
##
## This program was created for and tested in Linux Debian 8.


amixer set Capture 100% >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set Capture 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set Master 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set "Master Mono" 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set "Master Surround" 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set PCM 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set Line 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set CD 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set Mic 25% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set Headphone 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set "Headphone Jack Sense" 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set Aux 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set Video 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set Speaker 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set Phone 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set Center 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set LFE 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set "Stereo Mic" 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set "S/PDIF" 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set Surround 100% unmute >> /tmp/alsazz8.txt 2>&1
amixer -c 0 set Beep 0% mute >> /tmp/alsazz8.txt 2>&1
amixer set Master 75% >> /tmp/alsazz8.txt 2>&1

sleep 1

exit 0
