#!/bin/bash

# Copyright (C) 2014-2018 Jamil Said Jr
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
## This file is part of the powerzz program. This program will attempt
## to monitor battery levels and hibernate/shutdown the computer when the battery
## is close to be drained. This program relies on use of cron for scheduling battery
## checks. When battery reaches a low level (15%), a GUI pop-up will warn user
## about it. When battery reaches a critical level (7%) another GUI pop-up
## will appear and give the user the option of hibernating or doing nothing;
## if user doesn't choose in 30 seconds, the computer hibernates automatically.
## Battery levels are checked three times every minute. If user dismisses
## the critical battery warning, then there will be no more warnings until
## after a reboot or after the computer was (temporarily or not) recharged again.
## Users are able to choose from a GUI interface whether to turn on or off
## the battery monitor altogether, and whether the action should be  
## hibernate (default) or shutdown. 
##
## This program was created for and tested in Linux Debian 8.


### Below is a GLOBAL switch NOT reacheable via GUI, which is never supposed 
### to be used under normal circunstances. It disables powerzz for all 
### users regardless of user preferences.  
#exit 0 #powerzz-global-switch

#sleep a little to let things load when booting
sleep 10

#run first instance
nohup /usr/local/bin/powerzz4 > /dev/null 2>&1 &
sleep 19

#run second instance
nohup /usr/local/bin/powerzz4 > /dev/null 2>&1 &
sleep 19

#run third instance
nohup /usr/local/bin/powerzz4 > /dev/null 2>&1 &
sleep 3

exit 0
